project:
  type: website
  output-dir: docs

# # Layout horizontal (menus)
# website:
#   title: "Teaching"
#   navbar:
#     left:
#       - text: "Sobre"
#         href: index.qmd
#       - text: "Probabilidade"
#         menu:
#           - Probabilidade/LGN.qmd
#           - Probabilidade/TCL.qmd 

# Layout vertical (contents e sections)
website:
  title: "Teaching"
  repo-url: https://github.com/renanxcortes/teaching
  repo-actions: [edit, source, issue]
  reader-mode: true
  navbar:
    background: primary
    search: true
    left:
      - text: "Sobre"
        href: index.qmd
      - sidebar:discilinas
      
  sidebar:
    - id: discilinas
      title: "Temas"
      collapse-level: 2
      style: "docked"
      search: true
      contents:
        #- text: "Sobre"
        #  href: index.qmd
        - section: "Probabilidade"
          contents:
            - Probabilidade/LGN.qmd
            - Probabilidade/TCL.qmd

format:
  html:
    theme:
      - cosmo
    css: styles.css

editor: visual

bibliography: references.bib