project:
  type: website
  output-dir: docs

# # Layout horizontal (menus)
# website:
#   title: "Teaching"
#   navbar:
#     left:
#       - text: "Sobre"
#         href: index.qmd
#       - text: "Probabilidade"
#         menu:
#           - Probabilidade/LGN.qmd
#           - Probabilidade/TCL.qmd 
# 
# 
# Layout vertical (contents e sections)
website:
  title: "Teaching"
  repo-url: https://github.com/renanxcortes/teaching
  repo-actions: [edit, source, issue]
  reader-mode: true
  navbar:
    background: primary
    search: true
    left:
      - text: "Sobre"
        href: index.qmd
      - text: "Temas"
        menu:
          - sidebar:int_prob
          - sidebar:probabilidade_B
          - sidebar:multivariada

  sidebar:
    - id: int_prob
      title: "Introdução à Probabilidade"
      collapse-level: 2
      style: "docked"
      search: true
      contents:
        - section: "Conceitos Básicos"
          contents:
            - Int_Prob/experimento_aleatorio.qmd
            - Int_Prob/conceitos_de_probabilidade.qmd
            
            
    - id: probabilidade_B
      title: "Probabilidade B"
      collapse-level: 2
      style: "docked"
      search: true
      contents:
        - section: "Grandes Amostras"
          contents:
            - Probabilidade_B/LGN.qmd
            - Probabilidade_B/TCL.qmd
  
  
    - id: multivariada
      title: "Análise Multivariada"
      collapse-level: 2
      style: "docked"
      search: true
      contents:
        - section: "Principais Tópicos"
          contents:
            - Multivariada/Componentes_Principais.qmd
            - Multivariada/Cluster.qmd



format:
  html:
    theme:
      - cosmo
    css: styles.css

editor: visual

bibliography: references.bib