project:
  type: website
  output-dir: docs

website:
  title: "Teaching"
  navbar:
    left:
      - href: index.qmd
        text: Sobre
      - text: "Probabilidade"
        menu:
          - Probabilidade/LGN.qmd
          - Probabilidade/TCL.qmd 

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

