---
title: "Sobre"
lang: pt # Equações ficarem referenciadas em Português

execute: 
  warning: false
  message: false
  echo: false
---

Este é um Website do

Constante Evolução

Conceitos Gerais de Probabilidade, Estatística e afins

Sinta-se livre para sugerir melhorias abrindo uma issue [neste link](https://github.com/renanxcortes/teaching/issues)

Este é um website baseado no [Quarto](https://quarto.org/docs/websites) da empresa [Posit](https://posit.co/).

# Links Úteis

[Site oficial do Quarto](https://quarto.org/docs/websites)

[Templates úteis do prof. Gang He](https://drganghe.github.io/quarto-academic-site-examples.html)

[Site do prof. André Zibetti](https://www.inf.ufsc.br/~andre.zibetti/probabilidade/index.html)

# Considerações de Desenvolvimento do Site

O código para geração deste site por ser acessado [neste link](https://github.com/renanxcortes/teaching).

Para rodar códigos em Python, é necessário instalar as bibliotecas usando o reticulate. Especificamente, o Quarto cria um ambiente virtual temporário chamado `r-reticulate`. Ou seja, [as bibliotecas usadas durante a geração do site serão as bibliotecas instaladas neste ambiente](https://stackoverflow.com/questions/76745347/how-to-make-quarto-use-the-same-python-environment-that-was-specified-in-rstudio).

Exemplo de instalação de biblioteca do Python usando o `reticulate`:

```         
reticulate::py_install("matplotlib")
reticulate::py_install("scipy")
```

Além disso, cuidado com o gerenciamento das engines no momento de compilar o website. Segundo a documentação do Quarto, é importante sabermos as diferentes distinções de engine e suas coexistências conforme a seguir:

**Engine Conflicts:**

-   **Knitr vs. Jupyter:** *If you explicitly set the `engine` to `jupyter` in your YAML, R code chunks will not be executed, and only Python (or the kernel's language) will run. For mixed R and Python, `engine: knitr` is typically used, relying on `reticulate` for Python execution.*
