---
title: "Teorema Central do Limite"
lang: pt # Equações ficarem referenciadas em Português

toc: true
toc-title: "Nesta página"

execute: # Evitar colocar echo: false, caso contário os códigos não aparecerão
  warning: false
  message: false

format:
  html:
    code-fold: true
    code-summary: "Mostrar Código"
---

# Introdução e Condições Iniciais

O Teorema Central do Limite (TCL) é um dos resultados mais famosos e mais bonitos da Teoria da Probabilidade.

Sejam $X_1, X_2, ...$ variáveis aleatórias independentes e identicamente distribuídas ($iid$) com média e variância existentes e finitas. Isto é:

$-\infty < \mu < +\infty$

$0 < \sigma^2 < +\infty$

Além disso, defina $\bar{X} = \frac{\sum_{i=1}^{n}{X_i}}{n}$.

Pela Lei dos Grandes Números, sabemos que $\bar{X} \xrightarrow{n \rightarrow + \infty} \mu$, mas a qual taxa? Como que é a distribuição dessa quantidade?

## Convergência em Distribuição

**Definição. ** Sejam $X, X_1, X_2, ...$ variáveis aleatórias com, respectivamente, funções de distribuições $F, F_1, F_2, ...$. Dizemos que $X_n$ *converge em distribuição* para $X$, quando $n \rightarrow +\infty$, se $F_n(x) \rightarrow F(x)$ para todo $x$ ponto de continuidade de $F$.

*Notação: * $X_n \xrightarrow{D} X$ ou $X_n \xrightarrow{D} F$.

## Teorema Central do Limite

Podemos reescrever a quantidade da introdução como sendo $\bar{X} - \mu \xrightarrow{n \rightarrow + \infty} 0$. Assim, uma das maneiras de buscar entender a distribuição de uma quantidade quando ela vai zero é multiplicá-la por uma quantidade que vai para infinito de uma maneira que seu valor de convergência não "exploda" para o infinito e nem para zero. De fato se multiplicarmos a quantidade acima por $n$ elevando-o à um exponencial buscando controlar as taxas de convergência. Neste caso, o exponencial é o valor de $\frac{1}{2}$, ou seja, $\sqrt{n}$.^[Uma discussão sobre este fator de convergência é discutido [aqui](https://stats.stackexchange.com/questions/36113/where-does-sqrtn-come-from-in-central-limit-theorem-clt)] 

Logo, o TCL pode ser descrito por:

$\sqrt{n} \left(\bar{X} - \mu \right) \xrightarrow{n \rightarrow + \infty} N(0, \sigma^{2})$ em distribuição

Ou, alternativamente, na sua forma mais popular:

$$
\sqrt{n} \left(\frac{\bar{X} - \mu}{\sigma} \right) \xrightarrow{D} N(0, 1)
$$ {#eq-tcl}

O TCL retrata um dos teoremas mais lindos de toda a probabilidade tendo em vista que com poucas condições iniciais (neste caso, média e variância finitas) conseguimos provar que a média amostral $\bar{X}$ padronizada converge em distribuição para a distribuição normal padrão. Observe que o teorema não faz nenhuma alusão ao tipo de variável aleatória, podendo ser discreto ou contínuo, e nem sobre o suporte da distribuição, podendo ser positivo, negativo ou ambos.

Este teorema é um dos principais motivos pela ampla difusão da distribuição Normal em diversas áreas do conhecimento científico. Tendo em vista que, dadas às devidas condições, a média amostral pode ser aproximada pela distribuição normal padrão, as aplicações desses resultados são diversos.

**Prova.** Faça $S_n = X_1 + X_2 + ... +X_n$ e multiplicando e dividindo por $n$ o termo do @eq-tcl chegamos em

$$
\frac{1}{\sqrt{n}}\left(\frac{S_n - n\mu}{\sigma} \right) = \frac{1}{\sqrt{n}}\left(\frac{\sum_{i=1}^nX_i- n\mu}{\sigma} \right) \overset{\text{Expandindo o somatório}}{=} \frac{1}{\sqrt{n}}\sum_{i=1}^n\left(\frac{X_i- \mu}{\sigma} \right) \xrightarrow{n \rightarrow + \infty} N(0, 1)\ \text{em distribuição}
$$
Podemos assumir, sem perda de generalidade que $\mu = 0$ e $\sigma = 1$, pois poderíamos fazer a prova definindo uma variável aleatória sendo $Z_i = \frac{X_i- \mu}{\sigma}$, onde esta variável teria média 0 e desvio padrão 1. Sendo assim, basta fazer a prova para a quantidade:

$\frac{\sum_{i=1}^n X_i}{\sqrt{n}} \xrightarrow{D} N(0, 1)$

Para continuar a prova, faremos o uso da função geradora de momentos (M) da quantidade acima e avaliando o seu valor quanto $n \rightarrow +\infty$ a fim de identificar qual a distribuição limite obtida.^[Este teorema é um caso particular do [Teorema de Continuidade de Levy](https://en.wikipedia.org/wiki/L%C3%A9vy%27s_continuity_theorem) para funções características. E pode ser melhor detalhado em @curtiss1942note ou [aqui](https://researchers.ms.unimelb.edu.au/~xgge@unimelb/Files/Teaching/Advanced%20Probability%20(Semester%201%202020)/The%20Theory%20of%20Moment%20Generating%20Functions.pdf).] Ou seja:

$M_{X_n}(x) \xrightarrow{n \rightarrow + \infty} M_{X}(x) \implies X_n \xrightarrow{D} X$

Por notação, vamos estabelecer $Q_n = \frac{\sum_{i=1}^n X_i}{\sqrt{n}}$ e aplicar o teorema acima:

$M_{Q_n}(t) = E\left( e^{t\left(\frac{\sum_{i=1}^n X_i}{\sqrt{n}}\right)} \right) \overset{\text{Prop. de Exponencial}}{=} E\left( e^{\frac{tX_1}{\sqrt{n}}} \times e^{\frac{tX_2}{\sqrt{n}}} \times \dots \times e^{\frac{tX_n}{\sqrt{n}}} \right) \overset{\text{Independência}}{=} \prod_{i=1}^{n}E\left( e^{\frac{tX_i}{\sqrt{n}}} \right)$

Como todos os $X_i$ são identicamente distribuídos, podemos simplificar a expressão para:


$M_{Q_n}(t) = \prod_{i=1}^{n}E\left( e^{\frac{tX_i}{\sqrt{n}}} \right) = E\left( e^{\frac{tX_1}{\sqrt{n}}} \right) \times E\left( e^{\frac{tX_2}{\sqrt{n}}} \right) \times \dots \times E\left( e^{\frac{tX_n}{\sqrt{n}}} \right) = \left( E\left( e^{\frac{tX_i}{\sqrt{n}}} \right) \right)^n, \ \forall i$

No entanto, note acima que $E\left( e^{\frac{tX_i}{\sqrt{n}}} \right)$ é exatamente a função geradora de momentos aplicada no ponto $\frac{t}{\sqrt(n)}$. Logo:

$M_{Q_n}(t) = \left( M_{X_i}\left( \frac{t}{\sqrt{n}} \right) \right)^n, \ \forall i$

Assim, por simplificação de notação vamos suprimir o $X_i$ nos passos seguintes e vamos avaliar esta expressão o que acontece quando $n \rightarrow +\infty$.

Observe que da maneira como está estruturado $\left( M\left( \frac{t}{\sqrt{n}} \right) \right)^n$ converge para uma indefinição do tipo $1^\infty$, pois $\left( M\left( \frac{t}{\sqrt{n}} \right) \right)^n = \left( E\left( e^{\frac{tX}{\sqrt{n}}} \right) \right)^n \rightarrow \left( E\left( e^0 \right) \right)^\infty$.

Para tratar essa indefinição, aplicaremos o logaritmo natural ($log$) na expressão e, depois de avaliado o limite, podemos reverter o valor aplicando o exponencial. Logo,

$log\left(\left( M\left( \frac{t}{\sqrt{n}} \right) \right)^n \right) = n\times log\left( M\left( \frac{t}{\sqrt{n}} \right) \right)$

Quando aplicamos $n \rightarrow +\infty$ caímos numa indefinição do tipo $+\infty \times 0$, logo vamos reescrever a equação para caírmos numa indefinição do tipo $\frac{0}{0}$ para aplicarmos [l'Hôpital](https://pt.wikipedia.org/wiki/Regra_de_l%27H%C3%B4pital):

$\frac{log\left( M\left( \frac{t}{\sqrt{n}} \right) \right)}{\frac{1}{n}}$

Como o $n$ é um número inteiro natural e para melhor tratativa algébrica, vamos fazer uma transforção de variável para facilitar o desenvolvimento e poder aplicar a derivada em um número real. Assim,

$$
\lim_{n\to\infty}\frac{log\left( M\left( \frac{t}{\sqrt{n}} \right) \right)}{\frac{1}{n}} \overset{y=\frac{1}{\sqrt(n)}, \ y \in \mathbb{R} }{=} \lim_{y\to 0}\frac{log\left( M\left( yt \right) \right)}{y^2}
$$

Que é uma indefinição do tipo $\frac{0}{0}$. Logo, aplicando l'Hôpital:^[Lembrando que $\frac{d\log(f(x))}{dx} = \frac{1}{f(x)} \cdot \frac{df(x)}{dx} = \frac{f'(x)}{f(x)}$]

$$
\lim_{y\to 0}\frac{tM'(yt)}{M(yt)}\frac{1}{2y}
$$

Este limite continua sendo uma indefinição do tipo $\frac{0}{0}$, porque pela definição da função geradora do momento, quando aplicamos as suposições no ponto $t=0$ temos:

$$
\begin{aligned}
M(t) = E\left(e^{tX}\right) \implies M(0) = 1 \\
\mu = 0 \implies M'(0) = 0 \\
\sigma^2 = 1 \implies M''(0) = 1
\end{aligned}
$$
Logo, simplificando os limites e aplicando l'Hôpital novamente temos:

$$
\lim_{y\to 0}\frac{tM'(yt)}{M(yt)}\frac{1}{2y} \overset{\lim_{y\to 0}{M(yt)}=1}{=} \lim_{y\to 0}\frac{tM'(yt)}{2y} = \lim_{y\to 0}\frac{t^2M''(yt)}{2} = \frac{t^2}{2} \lim_{y\to 0}M''(yt) = \frac{t^2}{2}
$$

Aplicando o exponencial para reverter o logaritmo aplicado originalmente temos:

$M_{Q_n}(t) \xrightarrow{n \rightarrow +\infty} e^{\frac{t^2}{2}}$

Que coindide com a função geradora de momentos da Normal Padrão.

$\square$

Uma discussão mais aprofundada do Teorema Central do Limite pode ser encontrada no Capítulo 7 de @barryjames2023.

### Diferentes formulações e versões do TCL

@barryjames2023 trata o *problema central do limite* atavés do estudo da convergência em distribuição das somas parciais normalizadas e formula o TCL como sendo:

$\frac{{S}_n - E({S}_n)}{\sqrt{Var(S_n)}} \xrightarrow{D} N(0, 1)$

Outras maneiras de representar o TCL são:

$\frac{\bar{X} - E(\bar{X})}{\sqrt{Var(\bar{X})}} \xrightarrow{D} N(0, 1)$

$\sqrt{n} \bar{X} \xrightarrow{D} N(\mu, \sigma^2)$

## Exemplo Computacional

## Usando o TCL pra aproximar a Binomial pela Normal

Esta aproximação, também conhecida como [Teorema de De Moivre–Laplace](https://en.wikipedia.org/wiki/De_Moivre%E2%80%93Laplace_theorem), ...

# Links Úteis:

[Aula de Harvard de Lei dos Grandes Números e Teorema Central do Limite](https://www.youtube.com/watch?v=OprNqnHsVIA&t=1910s)

[Página da Wikipedia do Teorema Central do Limite](https://pt.wikipedia.org/wiki/Teorema_central_do_limite)
