---
title: "Funções de Variáveis Aleatórias"
lang: pt # Equações ficarem referenciadas em Português
toc: true
toc-title: "Nesta página"
toc-location: right
execute: 
  warning: false
  message: false
format:
  html:
    code-fold: true
    code-summary: "Mostrar Código"
---

# Introdução

Nesta seção vamos abordar alguns tópicos referentes à funções de variáveis aleatórias. Por definição, uma função $g(.)$ (por exemplo, uma transformação linear) aplicada à uma variável aleatória $X$, isto é, $g(X)$ também **será** uma variável aleatória. Analogamente, uma função $h(.)$ (por exemplo, uma soma) aplicada em um vetor aleatório $\textbf{X}$, isto é, $h(\textbf{X})$ **também será** uma variável aleatória.

# Funções de Variáveis Aleatórias Discretas

**Teorema** Seja $X$ uma distribuição discreta com distribuição massa de probabilidade $f_X$ e seja $Y = g(X)$ para alguma função de $g$ definida no conjunto de valores possíveis de $X$. Para cada valor possível $y$ de $Y$, a distribuição massa $f_Y$ de Y é

$$
f_Y(y) = P(Y = y) = P(g(X) = y) = \sum_{x:g(x) = y}f_X(x).
$$

Isto é, devemos somar os valores da dsitribuição original de $x$ nos novos pontos do novo domínio, isto é, o domínio de $y$. 

**Teorema** Seja $X$ uma distribuição discreta com distribuição massa de probabilidade $f_X$. Seja $a \in \mathbb{R}, a \ne 0$ and $b \in \mathbb{R}$, e seja $Y = aX + b$. Então, $f_Y(y) = P(Y = y) = P(aX + b = y) = P \left( X = \frac{y-b}{a} \right) = f_X\left(\frac{y-b}{a} \right)$


**Exemplo** Seja $X$ uma V.A. discreta com a seguinte forma:

<div style="width: fit-content; margin: auto;">

| $x$        | -2  | -1  | 0   | 1   | 2   |
|----------|-----|-----|-----|-----|-----|
| $P(X = x)$ | 1/5 | 1/5 | 1/5 | 1/5 | 1/5 |

</div>

A distribuição de $Y = X + 2$ é

<div style="width: fit-content; margin: auto;">

| $y$        | 0  | 1  | 2   | 3   | 4   |
|----------|-----|-----|-----|-----|-----|
| $P(Y = y)$ | 1/5 | 1/5 | 1/5 | 1/5 | 1/5 |

</div>

A distribuição de $Z = X^2$ é

<div style="width: fit-content; margin: auto;">

| $z$        | 0  | 1  | 2   |
|----------|-----|-----|-----|
| $P(Z = z)$ | 1/5 | 2/5 | 2/5 |

</div>



# Funções de Variáveis Aleatórias Contínuas

# Funções de Vetores Aleatórios

https://www.youtube.com/watch?v=tH-wuwvXmsk

https://www.youtube.com/watch?v=hC2idx2-GME

3.8 do degroot

convolucao
