---
title: "Conceitos de Probabilidade"
lang: pt # Equações ficarem referenciadas em Português

toc: true
toc-title: "Nesta página"
toc-location: right

execute: 
  warning: false
  message: false

format:
  html:
    code-fold: true
    code-summary: "Mostrar Código"
---

# Introdução

## Definição Clássica ($\Omega$ enumerável)

Segundo @magalhaes2006probabilidade, a definição clássica de probabilidade se refere à subconjuntos unitários equiprováveis. No caso enumerável finito temos:

$$
P(A) = \frac{Número\ de\ Elementos\ em\ A}{Número\ total\ de\ Elementos\ em\ \Omega}
$$

Se $\Omega$ tiver uma quantidade infinita de elementos, precisamos tratar a a definição acima com o uso de limites.

## Definição Clássica Geométrica ($\Omega$ não enumerável)

Quando $\Omega$ é não enumerável, o conceito se aplicará ao comprimento de intervalos, medidas de áreas ou similares, dando origem ao que chamamos de *probabilidade geométrica*. Por exemplo, se $\Omega$ é um intervalo onde $\Omega \in \mathbb{R}$, então:

$$
P(A) = \frac{Comprimento\ de\ A}{Comprimento\ de\ \Omega}
$$



## Definição Frequentista

A definição *frequentista* considera o limite de frequências relativas como o valor da probabilidade. Para tal, seja $n_{A}$ o número de ocorrências de $A$ em $n$ repetições independentes do experimento em questão. Assim,

$$
P(A) = \lim_{n\rightarrow{+\infty}} \frac{n_A}{n}
$$


## Probabilidade Axiomática

As definições anteriores não são suficientes para uma formulação matemática mais rigorosa da probabilidade. Assim, na primeira metade do século XX, @Kolmogorov1933 apresentou um conjunto de axiomas matemáticos para definir probabilidade e, assim, pavimentando toda a evolução da probabilidade moderna.

É importante, e ao mesmo tempo fascinante, destacar que apenas com esses três axiomas **todos os teoremas da Teoria da Probabilidade são viabilizados**. Assim, podemos destacar que toda a evolução da probabilidade foi pavimentada pelo trabalho de @Kolmogorov1933.

**Definição axiomática**

Assumindo que podemos atribuir um número real $P(A)$ para um evento $A$:

- **Axioma 1.** $P(A) \ge 0$

- **Axioma 2.** $P(\Omega) = 1$

- **Axioma 3.** Se $A_1, A_2, ..., A_n$ são disjuntos (2 a 2) (isto é, mutuamente excludentes), então

$$
P\left( \bigcup_{k=1}^{n} A_k \right) = \sum_{k=1}^{n} P (A_k) 
$$

(Os eventos são disjuntos 2 a 2, se $A_i \cap A_j = \emptyset, \forall i \ne j$)

Uma discussão mais aprofundada desses axiomas, incluindo uma versão mais conveniente para o Axioma 3 (para o caso $n = \infty$) e uma "Axioma 4" de *continuidade no vazio*, que pode ser derivado dos outros axiomas, é discutida no Capítulo 1 de @barryjames2023.


## Espaços de Probabilidade

Um [Espaço de Probabilidade](https://en.wikipedia.org/wiki/Probability_space) é um constructo que provê um modelo formal de um processo aleatório. Ele é composto por uma tríplice de valores $(\Omega, \mathcal{F}, P)$ onde

- $\Omega$ é todo o espaço amostral
- $\mathcal{F}$ (ou $\sigma$-álgebra) é o espaço de eventos (domínio)
- $P$ é uma função de probabilidade produz valores no intervalo $[0,1]$

Para um entendimento mais consistente da importância da definição de um espaço de probabilidade, bem como da importância da definição de uma $\sigma$-álgebra, que é o domínio do espaço, recomenda-se a leitura do Capítulo 1 de @barryjames2023, Capítulo 1 de @magalhaes2006probabilidade, Capítulo 2B e 12 de @axler2020measure.^[É possível que esses conceitos sejam mais difíceis de assimilar do ponto de vista prático. No entanto, eles são fundamentais para garantir uma base matemática sólida para toda a teoria da probbilidade. As propriedades desejáveis de uma $\sigma$-álgebra garantem que o espaço de probabilidade é um espaço mensurável. Por exemplo, uma das condições é a *aditividade contável* (isto é, se $A_1$ e $A_2$ são dois eventos sendo $A_1 \in \mathcal{F}$ e $A_2 \in \mathcal{F}$, então $(A_1 \cup A_2) \in \mathcal{F}$). Se essa condição não fosse satisfeita, seria possível aplicar o terceiro axioma de Kolmogorov e chegar em inconsistências como probabilidades maior que 1. Por exemplo, suponha $\mathcal{F} = \{ \emptyset, \Omega, \{1\}, \{2\}, \{1,3\}, \{2,3\} \}$ **não** é uma $\sigma$-álgebra pois $\{1, 2\} \notin \mathcal{F}$ e, portanto, $P(\{1, 2\})$ é **indefinido**... ao aplicarmos o terceiro axioma de Kolmogorov ] 


Por ora, recomendo fortemente o leitor a assitir o vídeo [Bertrand's Paradox (with 3blue1brown) - Numberphile](https://www.youtube.com/watch?v=mZBwsm6B280) (explicação do Exemplo 1.8 de @magalhaes2006probabilidade) para esclarecer qual o efeito da definição de diferentes espaços de probabiidade para um mesmo problema e assim produzir probabilidades significativamente diferentes dependendo da maneira como são definidos $\Omega$ e $\sigma$-álgebra e, assim, produzindo diferentes processos geradores de eventos.



alguns conceitos de Teoria da Medida aditividade contável

falr video do veritaium


https://en.wikipedia.org/wiki/Banach%E2%80%93Tarski_paradox
Vitali Set
Axioma da escolha
